defaultBaseImage: gcr.io/distroless/static-debian12:nonroot
builds:
- main: .
  env:
  - CGO_ENABLED=0
# If you need support for the the "createca" command, you must enable
# CGO and use a base image with gblic (base instead of static)
#  - CGO_ENABLED=1
  flags:
  - -trimpath
  - -tags
  - "{{ .Env.GIT_HASH }}"
  - -tags
  - "{{ .Env.GIT_VERSION }}"
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
